analyzer: Analyzer::Device::Resistor Class Reference
Analyzer::Device::Resistor Class Reference
Resistor.
#include <Resistor.h>
Public Member Functions
Resistor (unsigned id, unsigned port_plus, unsigned port_minus, double R)
Initialize a new resistor.
double equation (LinMath::Matrix &)
Write equation.
std::string print ()
Print this resistor in human-readable format.
Public Member Functions inherited from Analyzer::Device::IDevice
IDevice (unsigned id, unsigned plus, unsigned minus)
Construct device base common to all devices.
unsigned other_port (unsigned port)
Get other port if one port is given.
int sign (unsigned port)
Sign of this device as seen from port.
unsigned currentIndex ()
Get current index of this device.
unsigned voltageIndex ()
Get voltage index of this device.
virtual ~IDevice ()
(empty) virtual destructor for futureproofing.
Private Attributes
double resistance
resistance (who would have quessed it?)
Additional Inherited Members
Public Attributes inherited from Analyzer::Device::IDevice
const unsigned port_plus
plus connection (node ID)
const unsigned port_minus
minus connection (node ID)
const unsigned id
ID of self.
Static Protected Member Functions inherited from Analyzer::Device::IDevice
static unsigned currentIndexFromId (unsigned id)
Current index helper when writing equations into the matrix.
static unsigned voltageIndexFromId (unsigned id)
Voltage index helper when writing equations into the matrix.
Detailed Description
Resistor.
Parameter: resistance Equation: iR - u = 0
Definition at line 12 of file Resistor.h.
Constructor & Destructor Documentation
Resistor()
Resistor::Resistor (unsigned id, unsigned port_plus, unsigned port_minus, double R)
Initialize a new resistor.
Parameters
id
port_plus
port_minus
R
Definition at line 7 of file Resistor.cpp.
                                                                                  : IDevice(id, port_plus, port_minus), resistance(R)
 {
 }
Member Function Documentation
equation()
double Resistor::equation (LinMath::Matrix & eq) virtual
Write equation.
See class description for equation, and IDevice::equation for details on this function
Parameters
eq
Returns
Implements Analyzer::Device::IDevice.
Definition at line 11 of file Resistor.cpp.
 {
     eq(id - 1, voltageIndex()) = -1.0;
     eq(id - 1, currentIndex()) = resistance;
     return 0.0;
 }
References Analyzer::Device::IDevice::currentIndex(), resistance, and Analyzer::Device::IDevice::voltageIndex().
Referenced by Analyzer::Network::Solvers::NetworkSolverGen::solve().
print()
std::string Resistor::print () virtual
Print this resistor in human-readable format.
Returns
string representation of this resistor
Implements Analyzer::Device::IDevice.
Definition at line 19 of file Resistor.cpp.
 {
     return fmt::format("Resistor(id={}, plus={}, minus={}, resistance={})", id, port_plus, port_minus, resistance);
 }
References Analyzer::Device::IDevice::port_minus, Analyzer::Device::IDevice::port_plus, and resistance.
Member Data Documentation
resistance
double Analyzer::Device::Resistor::resistance private
resistance (who would have quessed it?)
Definition at line 16 of file Resistor.h.
Referenced by equation(), and print().
The documentation for this class was generated from the following files:
Device/Resistor.h
Device/Resistor.cpp