analyzer: Analyzer::Network::Solvers::NetworkSolverTwoport Class Reference
Analyzer::Network::Solvers::NetworkSolverTwoport Class Reference
Network solver for two port characteristic matrices.
#include <NetworkSolverTwoport.h>
Public Member Functions
NetworkSolverTwoport (unsigned primaryID, unsigned secondaryID)
Initialize a solver with port termination devices.
LinMath::Matrix solve (LinMath::Matrix &eqOrig) const
Solve for characteristic matrices.
std::string print () const
Print the solver in a human readable format.
std::string validate (unsigned N, unsigned B)
Validate the solver.
Private Attributes
const unsigned primary
primary port termination device ID
const unsigned secondary
secondary port termination device ID
Detailed Description
Network solver for two port characteristic matrices.
Returns a 12x2 matrix, containing the 6 characteristic matrices (R, G, H, K, A, B). If any of them does not exitst, it'll be NaN-d
Definition at line 12 of file NetworkSolverTwoport.h.
Constructor & Destructor Documentation
NetworkSolverTwoport()
NetworkSolverTwoport::NetworkSolverTwoport (unsigned primaryID, unsigned secondaryID)
Initialize a solver with port termination devices.
Parameters
primaryID
secondaryID
Definition at line 11 of file NetworkSolverTwoport.cpp.
                                                                                    : primary(primaryID), secondary(secondaryID)
 {
 }
Member Function Documentation
print()
std::string NetworkSolverTwoport::print () const virtual
Print the solver in a human readable format.
Returns
string representation of the solver
Implements Analyzer::Network::INetworkSolver.
Definition at line 108 of file NetworkSolverTwoport.cpp.
 {
     return fmt::format("NetworkSolverTwoport(primary={}, secondary={})", primary, secondary);
 }
References primary, and secondary.
solve()
LinMath::Matrix NetworkSolverTwoport::solve (LinMath::Matrix & eqOrig) const virtual
Solve for characteristic matrices.
Parameters
eqOrig
Returns
the 12x2 matrix as described in the class's description
Implements Analyzer::Network::INetworkSolver.
Definition at line 63 of file NetworkSolverTwoport.cpp.
 {
     // remove 2 equations
     LinMath::Matrix target(2, 1);
     target(0, 0) = primary - 1;
     target(1, 0) = secondary - 1;
     auto pM = permuteMatrix(eqOrig.rows, target);
     LinMath::Matrix eq = (pM * eqOrig).subMatrix(2, 0, eqOrig.rows - 2, eqOrig.columns);
     for (unsigned r = 0; r < eq.rows; r++) {
         eq(r, 2 * primary - 1) *= -1.0;
         eq(r, 2 * secondary - 1) *= -1.0;
     }
     LinMath::Matrix result(12, 2);
     auto impedance = solve_or_nan(2 * primary - 2, 2 * secondary - 2, 2 * primary - 1, 2 * secondary - 1, eq).subMatrix(0, 0, 2, 2);
     copy_matrix(impedance, result, 0);
     auto conductance = solve_or_nan(2 * primary - 1, 2 * secondary - 1, 2 * primary - 2, 2 * secondary - 2, eq).subMatrix(0, 0, 2, 2);
     copy_matrix(conductance, result, 2);
     auto hybrid = solve_or_nan(2 * primary - 2, 2 * secondary - 1, 2 * primary - 1, 2 * secondary - 2, eq).subMatrix(0, 0, 2, 2);
     copy_matrix(hybrid, result, 4);
     auto invhybrid = solve_or_nan(2 * primary - 1, 2 * secondary - 2, 2 * primary - 2, 2 * secondary - 1, eq).subMatrix(0, 0, 2, 2);
     copy_matrix(invhybrid, result, 6);
     // chain type characteristics use a differenc reference direction for i2
     for (unsigned r = 0; r < eq.rows; r++) {
         eq(r, 2 * secondary - 1) *= -1.0;
     }
     auto chain = solve_or_nan(2 * primary - 2, 2 * primary - 1, 2 * secondary - 2, 2 * secondary - 1, eq).subMatrix(0, 0, 2, 2);
     copy_matrix(chain, result, 8);
     auto invchain = solve_or_nan(2 * secondary - 2, 2 * secondary - 1, 2 * primary - 2, 2 * primary - 1, eq).subMatrix(0, 0, 2, 2);
     copy_matrix(invchain, result, 10);
     return result;
 }
References LinMath::Matrix::columns, copy_matrix(), permuteMatrix(), primary, LinMath::Matrix::rows, secondary, solve_or_nan(), and LinMath::Matrix::subMatrix().
validate()
std::string Analyzer::Network::Solvers::NetworkSolverTwoport::validate (unsigned N, unsigned B) virtual
Validate the solver.
both device IDs must be valid
Parameters
N
B
Returns
error string or empty string
Implements Analyzer::Network::INetworkSolver.
Definition at line 113 of file NetworkSolverTwoport.cpp.
 {
     if (primary == 0 || primary > B) {
         return fmt::format("primary device {} is invalid!", primary);
     }
     if (secondary == 0 || secondary > B) {
         return fmt::format("secondary device {} is invalid!", secondary);
     }
     if (primary == secondary) {
         return fmt::format("TWOPORT's ports can't be the same!");
     }
     return "";
 }
Member Data Documentation
primary
const unsigned Analyzer::Network::Solvers::NetworkSolverTwoport::primary private
primary port termination device ID
Definition at line 16 of file NetworkSolverTwoport.h.
Referenced by print(), and solve().
secondary
const unsigned Analyzer::Network::Solvers::NetworkSolverTwoport::secondary private
secondary port termination device ID
Definition at line 18 of file NetworkSolverTwoport.h.
Referenced by print(), and solve().
The documentation for this class was generated from the following files:
Network/Solver/NetworkSolverTwoport.h
Network/Solver/NetworkSolverTwoport.cpp