analyzer: Analyzer::Network::Network Class Reference
Analyzer::Network::Network Class Reference
Class representing a linear resistive network.
#include <Network.h>
Public Member Functions
Network (unsigned N, unsigned B, std::unique_ptr< INetworkSolver > solver)
Initialize empty network with capacity and solver.
void addDevice (std::unique_ptr< Analyzer::Device::IDevice > device)
Add one device to the network.
void finishLoading ()
Sort devices by ID.
LinMath::Matrix getEquations ()
Generate equation system of the network.
LinMath::Matrix solve ()
Solve the network using the solver. The meaning of the solution matrix depends on the solver used.
unsigned getBranchCount () const
Get current branch count (used while loading).
Public Attributes
const unsigned N
number of nodes of the network graph
const unsigned B
number of branches of the network graph (number of devices)
Private Attributes
NetworkGraph graph
Branches branches
std::unique_ptr< INetworkSolver > solver
a pointer to the solver object of the network
Detailed Description
Class representing a linear resistive network.
Stores network and produces equations for solving.
Definition at line 23 of file Network.h.
Constructor & Destructor Documentation
Network()
Network::Network (unsigned N, unsigned B, std::unique_ptr< INetworkSolver > solver)
Initialize empty network with capacity and solver.
Parameters
N number of nodes
B number of branches
solver solver object
Definition at line 16 of file Network.cpp.
                                                                              : N(N), B(B), graph(N), solver(std::move(solver))
 {
 }
Member Function Documentation
addDevice()
void Network::addDevice (std::unique_ptr< Analyzer::Device::IDevice > device)
Add one device to the network.
Parameters
device
Exceptions
LoadException if the device ID is invalid (0 or >B)
LoadException if a device with the same ID is already added
LoadException if either port of the device is invalid (0 or >N)
Definition at line 20 of file Network.cpp.
 {
     // check if the ID is valid
     if (device->id == 0 || device->id > B) {
         throw LoadException(fmt::format("Device ID {} is outside of the allowed range 1..{}", device->id, B));
     }
     // check if the ID is not a duplicate one
     if (std::any_of(branches.begin(), branches.end(), [&device](std::unique_ptr<IDevice>& test) {return device->id == test->id; })) {
         throw LoadException(fmt::format("Device ID {} is already taken!", device->id));
     }
     // validate ports
     if (device->port_minus == 0 || device->port_minus > N) {
         throw LoadException(fmt::format("Invalid minus port of device: {}", device->print()));
     }
     if (device->port_plus == 0 || device->port_plus > N) {
         throw LoadException(fmt::format("Invalid plus port of device: {}", device->print()));
     }
     graph[device->port_plus - 1].push_back(device->id);
     graph[device->port_minus - 1].push_back(0 - device->id);
     branches.push_back(std::move(device));
 }
References B, branches, graph, and N.
finishLoading()
void Network::finishLoading ()
Sort devices by ID.
Definition at line 46 of file Network.cpp.
 {
     std::sort(branches.begin(), branches.end(), [](std::unique_ptr<IDevice>& a, std::unique_ptr<IDevice>& b) {
         return a->id < b->id;
         });
 }
References branches.
Referenced by getEquations().
getBranchCount()
unsigned Analyzer::Network::Network::getBranchCount () const
Get current branch count (used while loading).
Returns
the number of already added branches
Definition at line 112 of file Network.cpp.
 {
     return branches.size();
 }
getEquations()
LinMath::Matrix Network::getEquations ()
Generate equation system of the network.
It'll be
B characteristic equations of devices sorted by ID ascending
N-1 Kirchoff's node laws (no particular order)
B-N+1 Kirchoff's voltage laws (no particular order)
Returns
the equation system's extended matrix
Definition at line 53 of file Network.cpp.
{
     this->finishLoading();
     LinMath::Matrix eq(2 * B, 2 * B + 1);
     // unknowns: u0, i0, u1, i1, ...
     unsigned idx = B;
     // characteristic equations of nodes
     for (auto& branch : branches) {
         eq(branch->id - 1, 2 * B) = branch->equation(eq);
     }
     // node equations
     // basicly KIRCHOFF's NODE LAWS
     // so current going into a node equals the current going out
     // find relevant nodes
     // all but one from each component
     // with DFS we can find the components
     // and since we marked their roots
     // we can just take every node EXCEPT them
     auto parent = std::vector<int>(N);;
     std::vector<int> binding_branches;
     DFS(graph, branches, binding_branches, parent);
     for (unsigned i = 0; i < N; i++) {
         if (parent[i] != 0) {
             for (auto it = graph[i].begin(); it != graph[i].end(); it++) {
                 eq(idx, 2 * abs(*it) - 1) = (*it > 0) ? 1 : -1;
             }
             idx++;
         }
     }
     // cycles
     // Kirchoff's voltage laws (KVLs)
     // going round in a loop, the sum of all voltages (with proper directions) is 0
     auto cycles = findCycles(graph, branches);
     for (auto& cycle : *cycles) {
         for (auto& b : cycle) {
             eq(idx, 2 * abs(b) - 2) = (b > 0) ? 1 : -1;
         }
         idx++;
     }
     return eq;
 }
References B, branches, Analyzer::Network::DFS(), Analyzer::Network::findCycles(), finishLoading(), graph, and N.
Referenced by solve().
solve()
LinMath::Matrix Network::solve ()
Solve the network using the solver. The meaning of the solution matrix depends on the solver used.
Returns
a matrix representing the solution
Exceptions
SolveException if anything goes wrong
Definition at line 102 of file Network.cpp.
{
     try {
         auto eq = getEquations();
         return solver->solve(eq);
     }
     catch (const std::exception& e) {
         throw SolveException(e.what());
     }
 }
References getEquations(), and solver.
Member Data Documentation
B
const unsigned Analyzer::Network::Network::B
number of branches of the network graph (number of devices)
Definition at line 40 of file Network.h.
Referenced by addDevice(), and getEquations().
branches
Branches Analyzer::Network::Network::branches private
list of branches of the network graph generally unsorted, but finishLoading() sorts it ascending by ID
Definition at line 32 of file Network.h.
Referenced by addDevice(), finishLoading(), and getEquations().
graph
NetworkGraph Analyzer::Network::Network::graph private
the network graph itself stored as an outgoing adjecency list format with signed IDs of the devices / branches positive means outgoing, negative is incoming
Definition at line 29 of file Network.h.
Referenced by addDevice(), and getEquations().
N
const unsigned Analyzer::Network::Network::N
number of nodes of the network graph
Definition at line 38 of file Network.h.
Referenced by addDevice(), and getEquations().
solver
std::unique_ptr<INetworkSolver> Analyzer::Network::Network::solver private
a pointer to the solver object of the network
Definition at line 35 of file Network.h.
Referenced by solve().
The documentation for this class was generated from the following files:
Network/Network.h
Network/Network.cpp