analyzer: Analyzer::Network::Solvers::NetworkSolverResistance Class Reference
Analyzer::Network::Solvers::NetworkSolverResistance Class Reference
Network solver to determine equivalent resistance of a network.
#include <NetworkSolverResistance.h>
Public Member Functions
NetworkSolverResistance (unsigned device)
Initialize solver using a termination device ID.
LinMath::Matrix solve (LinMath::Matrix &eqOrig) const
Solve for the equivalent resistance of the network seen from the termination device.
std::string print () const
Convert to a human readable format.
std::string validate (unsigned N, unsigned B)
Validate the solver.
Private Attributes
const unsigned port
termination device ID
Detailed Description
Network solver to determine equivalent resistance of a network.
Definition at line 10 of file NetworkSolverResistance.h.
Constructor & Destructor Documentation
NetworkSolverResistance()
Analyzer::Network::Solvers::NetworkSolverResistance::NetworkSolverResistance (unsigned device)
Initialize solver using a termination device ID.
Parameters
device
Definition at line 8 of file NetworkSolverResistance.cpp.
                                                                                       : port(device)
 {
 }
Member Function Documentation
print()
std::string Analyzer::Network::Solvers::NetworkSolverResistance::print () const virtual
Convert to a human readable format.
Returns
string representation of the solver
Implements Analyzer::Network::INetworkSolver.
Definition at line 43 of file NetworkSolverResistance.cpp.
 {
     return fmt::format("NetworkSolverResistance(port={})", port);
 }
solve()
LinMath::Matrix Analyzer::Network::Solvers::NetworkSolverResistance::solve (LinMath::Matrix & eqOrig) const virtual
Solve for the equivalent resistance of the network seen from the termination device.
Parameters
eqOrig extended equation system matrix
Returns
1x1 matrix with the resistance
Exceptions
SolveException if the 0-current termination voltage is not 0
Implements Analyzer::Network::INetworkSolver.
Definition at line 12 of file NetworkSolverResistance.cpp.
 {
     LinMath::Matrix eq = eqOrig;
     // remove the equation of our device
     for (unsigned c = 0; c < eq.columns; c++)
         eq(port - 1, c) = 0.0;
     // assert that terminating with a 0-current device, we have no voltage
     CurrentSource probe(port, 0, 0, 0.0);
     eq(port - 1, eq.columns - 1) = probe.equation(eq);
     double v0 = (eq.subMatrix(0, 0, eq.rows, eq.columns - 1).invert() * eq.subMatrix(0, eq.columns - 1, eq.rows, 1))(2 * port - 2, 0);
     if (v0 != 0.0) {
         throw Analyzer::Network::SolveException(fmt::format("Zero current voltage is not 0!"));
     }
     // voltage response of the network to a 1A stimulus is the resistance
     // take into care the direction of the current
     CurrentSource gen(port, 0, 0, -1.0);
     eq(port - 1, eq.columns - 1) = gen.equation(eq);
     double res = (eq.subMatrix(0, 0, eq.rows, eq.columns - 1).invert() * eq.subMatrix(0, eq.columns - 1, eq.rows, 1))(2 * port - 2, 0);
     LinMath::Matrix result(1, 1);
     result(0, 0) = res;
     return result;
 }
References LinMath::Matrix::columns, Analyzer::Device::CurrentSource::equation(), LinMath::Matrix::invert(), LinMath::Matrix::rows, and LinMath::Matrix::subMatrix().
validate()
std::string Analyzer::Network::Solvers::NetworkSolverResistance::validate (unsigned N, unsigned B) virtual
Validate the solver.
termination device ID should be valid
Parameters
N
B
Returns
error string or empty string
Implements Analyzer::Network::INetworkSolver.
Definition at line 48 of file NetworkSolverResistance.cpp.
 {
     if (port == 0 || port > B) {
         return fmt::format("device {} is invalid!", port);
     }
     return "";
 }
Member Data Documentation
port
const unsigned Analyzer::Network::Solvers::NetworkSolverResistance::port private
termination device ID
Definition at line 14 of file NetworkSolverResistance.h.
The documentation for this class was generated from the following files:
Network/Solver/NetworkSolverResistance.h
Network/Solver/NetworkSolverResistance.cpp