analyzer: Analyzer::Device::IDevice Class Reference
Analyzer::Device::IDevice Class Reference abstract
Abstract base class of devices.
#include <IDevice.h>
Public Member Functions
IDevice (unsigned id, unsigned plus, unsigned minus)
Construct device base common to all devices.
unsigned other_port (unsigned port)
Get other port if one port is given.
int sign (unsigned port)
Sign of this device as seen from port.
virtual double equation (LinMath::Matrix &eq)=0
Write characteristic equation of this node into the matrix.
unsigned currentIndex ()
Get current index of this device.
unsigned voltageIndex ()
Get voltage index of this device.
virtual std::string print ()=0
Print this device in a human-readable format.
virtual ~IDevice ()
(empty) virtual destructor for futureproofing.
Public Attributes
const unsigned port_plus
plus connection (node ID)
const unsigned port_minus
minus connection (node ID)
const unsigned id
ID of self.
Static Protected Member Functions
static unsigned currentIndexFromId (unsigned id)
Current index helper when writing equations into the matrix.
static unsigned voltageIndexFromId (unsigned id)
Voltage index helper when writing equations into the matrix.
Detailed Description
Abstract base class of devices.
Devices have 2 connections (plus and minus), have a voltage drop, current and a characteristic equation describing the relationship between those 2.
Devices are responsible for writing their characteristic equations into the extended equation system matrix. This happens in a fixed order (sorted by ID), so they MIGHT overwrite other devices equations (this is needed by Nullator, and I could not eliminate this requirement).
Signs of voltage and current:
voltage drop is positive if the plus connection is at higher potential
current is positive if it's going into the plus connection
Definition at line 22 of file IDevice.h.
Constructor & Destructor Documentation
IDevice()
IDevice::IDevice (unsigned id, unsigned plus, unsigned minus)
Construct device base common to all devices.
Parameters
id
plus
minus
Definition at line 14 of file IDevice.cpp.
                                                            : port_plus(plus), port_minus(minus), id(id)
 {
 }
~IDevice()
IDevice::~IDevice () virtual
(empty) virtual destructor for futureproofing.
Definition at line 42 of file IDevice.cpp.
 {
 }
Member Function Documentation
currentIndex()
unsigned IDevice::currentIndex ()
Get current index of this device.
Returns
index of the current of this device in the matrix
Definition at line 32 of file IDevice.cpp.
 {
     return IDevice::currentIndexFromId(id);
 }
References currentIndexFromId().
Referenced by Analyzer::Device::Resistor::equation(), Analyzer::Device::CCCS::equation(), Analyzer::Device::CurrentSource::equation(), Analyzer::Device::Nullator::equation(), Analyzer::Device::Probe::equation(), and Analyzer::Device::VCCS::equation().
currentIndexFromId()
unsigned IDevice::currentIndexFromId (unsigned id) static protected
Current index helper when writing equations into the matrix.
Parameters
id id of device to get current index of
Returns
unknown index of the current of the given device
Definition at line 6 of file IDevice.cpp.
 {
     return 2 * id - 1;
 }
Referenced by currentIndex(), Analyzer::Device::CCCS::equation(), and Analyzer::Device::CCVS::equation().
equation()
virtual double Analyzer::Device::IDevice::equation (LinMath::Matrix & eq) pure virtual
Write characteristic equation of this node into the matrix.
Parameters
eq matrix to write variable coefficents
Returns
free component of the equation
Implemented in Analyzer::Device::VCVS, Analyzer::Device::VCCS, Analyzer::Device::Probe, Analyzer::Device::Nullator, Analyzer::Device::CurrentSource, Analyzer::Device::CCVS, Analyzer::Device::CCCS, Analyzer::Device::Wire, Analyzer::Device::VoltageSource, and Analyzer::Device::Resistor.
other_port()
unsigned IDevice::other_port (unsigned port)
Get other port if one port is given.
If the port is neither plus nor minus port, it returns 0. Since this, care must be taken to ensure that port is valid
Parameters
port
Returns
other port or 0
Definition at line 18 of file IDevice.cpp.
 {
     if (port == port_plus)
         return port_minus;
     if (port == port_minus)
         return port_plus;
     return 0;
 }
References port_minus, and port_plus.
print()
virtual std::string Analyzer::Device::IDevice::print () pure virtual
Print this device in a human-readable format.
Returns
string representation of this device
Implemented in Analyzer::Device::Wire, Analyzer::Device::VoltageSource, Analyzer::Device::VCVS, Analyzer::Device::VCCS, Analyzer::Device::Resistor, Analyzer::Device::Probe, Analyzer::Device::Nullator, Analyzer::Device::CurrentSource, Analyzer::Device::CCVS, and Analyzer::Device::CCCS.
sign()
int IDevice::sign (unsigned port)
Sign of this device as seen from port.
1 if port is plus port
-1 otherwise
Since this care must be taken to only call this function with one of the ports of this device
Parameters
port
Returns
sign of this device
Definition at line 27 of file IDevice.cpp.
 {
     return port == port_plus ? 1 : -1;
 }
References port_plus.
voltageIndex()
unsigned IDevice::voltageIndex ()
Get voltage index of this device.
Returns
index of the voltage of this device in the matrix
Definition at line 37 of file IDevice.cpp.
 {
     return IDevice::voltageIndexFromId(id);
 }
References voltageIndexFromId().
Referenced by Analyzer::Device::Resistor::equation(), Analyzer::Device::VoltageSource::equation(), Analyzer::Device::Wire::equation(), Analyzer::Device::CCVS::equation(), Analyzer::Device::Nullator::equation(), and Analyzer::Device::VCVS::equation().
voltageIndexFromId()
unsigned IDevice::voltageIndexFromId (unsigned id) static protected
Voltage index helper when writing equations into the matrix.
Parameters
id id of device to get voltage index of
Returns
unknown index of the voltage of the given device
Definition at line 10 of file IDevice.cpp.
 {
     return 2 * id - 2;
 }
Referenced by Analyzer::Device::VCCS::equation(), Analyzer::Device::VCVS::equation(), and voltageIndex().
Member Data Documentation
id
const unsigned Analyzer::Device::IDevice::id
ID of self.
Definition at line 45 of file IDevice.h.
port_minus
const unsigned Analyzer::Device::IDevice::port_minus
minus connection (node ID)
Definition at line 43 of file IDevice.h.
Referenced by other_port(), Analyzer::Device::CCCS::print(), Analyzer::Device::CCVS::print(), Analyzer::Device::CurrentSource::print(), Analyzer::Device::Nullator::print(), Analyzer::Device::Probe::print(), Analyzer::Device::Resistor::print(), Analyzer::Device::VCCS::print(), Analyzer::Device::VCVS::print(), Analyzer::Device::VoltageSource::print(), and Analyzer::Device::Wire::print().
port_plus
const unsigned Analyzer::Device::IDevice::port_plus
plus connection (node ID)
Definition at line 41 of file IDevice.h.
Referenced by other_port(), Analyzer::Device::CCCS::print(), Analyzer::Device::CCVS::print(), Analyzer::Device::CurrentSource::print(), Analyzer::Device::Nullator::print(), Analyzer::Device::Probe::print(), Analyzer::Device::Resistor::print(), Analyzer::Device::VCCS::print(), Analyzer::Device::VCVS::print(), Analyzer::Device::VoltageSource::print(), Analyzer::Device::Wire::print(), and sign().
The documentation for this class was generated from the following files:
Device/IDevice.h
Device/IDevice.cpp