analyzer: Network/Solver/NetworkSolverTwoport.cpp File Reference
NetworkSolverTwoport.cpp File Reference
#include "NetworkSolverTwoport.h"
#include <LinMath/InvertException.h>
#include <fmt/core.h>
#include <iostream>
#include <algorithm>
#include <limits>
Functions
LinMath::Matrix permuteMatrix (unsigned n, LinMath::Matrix targets)
generate a permute matrix.
LinMath::Matrix solve_for (unsigned for1, unsigned for2, unsigned from1, unsigned from2, LinMath::Matrix &eq)
solve for 2 unknowns from 2 others.
void copy_matrix (LinMath::Matrix &from, LinMath::Matrix &to, unsigned row)
copy a 2x2 matrix into a bigger matrix starting at row.
LinMath::Matrix solve_or_nan (unsigned for1, unsigned for2, unsigned from1, unsigned from2, LinMath::Matrix &eq)
solve_for but catch any exception and NaN the matrix instead.
Function Documentation
copy_matrix()
void copy_matrix (LinMath::Matrix & from, LinMath::Matrix & to, unsigned row)
copy a 2x2 matrix into a bigger matrix starting at row.
Parameters
from matrix to copy from
to matrix to copy to
row copy to that row
Definition at line 173 of file NetworkSolverTwoport.cpp.
{
     for (unsigned r = 0; r < 2; r++) {
         for (unsigned c = 0; c < 2; c++) {
             to(r + row, c) = from(r, c);
         }
     }
     // this could be 1 line shorter if I unrolled the loop by hand...
 }
Referenced by Analyzer::Network::Solvers::NetworkSolverTwoport::solve().
permuteMatrix()
LinMath::Matrix permuteMatrix (unsigned n, LinMath::Matrix targets)
generate a permute matrix.
It will have 1s in the specified columns for the first rows, one in each row it will be a N x N matrix
Parameters
n number of rows & columns of the result matrix
targets target columns to place 1s into
Returns
generated permute matrix
Definition at line 151 of file NetworkSolverTwoport.cpp.
{
     LinMath::Matrix m(n, n);
     for (unsigned i = 0; i < targets.rows; i++) {
         m(i, (unsigned)targets(i, 0)) = 1.0;
     }
     unsigned r = targets.rows;
     for (unsigned c = 0; c < n; c++) {
         // write ONLY IF not in targets
         bool contains = false;
         for (unsigned i = 0; i < targets.rows; i++) {
             if (targets(i, 0) == c) {
                 contains = true;
             }
         }
         if (!contains) {
             m(r++, c) = 1.0;
         }
     }
     return m;
 }
References LinMath::Matrix::rows.
Referenced by Analyzer::Network::Solvers::NetworkSolverTwoport::solve(), and solve_for().
solve_for()
LinMath::Matrix solve_for (unsigned for1, unsigned for2, unsigned from1, unsigned from2, LinMath::Matrix & eq)
solve for 2 unknowns from 2 others.
Uses a permute matrix to reorder, then uses simple matrix arithmetics Assumes no constant is added
Parameters
for1
for2
from1
from2
eq equation system to solve in
Returns
2x2 matrix
Definition at line 127 of file NetworkSolverTwoport.cpp.
{
     // swap in lines, chop up matrix, invert and multiply
     auto mat = eq.subMatrix(0, 0, eq.rows, eq.columns - 1);
     auto vec = eq.subMatrix(0, eq.columns - 1, eq.rows, 1);
     // swap columns
     // for1, for2, from1, from2
     LinMath::Matrix ptarget(4, 1);
     ptarget(0, 0) = from1;
     ptarget(1, 0) = from2;
     ptarget(2, 0) = for1;
     ptarget(3, 0) = for2;
     auto pM = permuteMatrix(mat.columns, ptarget).transpose();
     auto matPermuted = mat * pM;
     auto m1 = matPermuted.subMatrix(0, 0, mat.rows, 2);
     auto m2 = matPermuted.subMatrix(0, 2, mat.rows, mat.columns - 2);
     auto resM = m2.invert() * m1 * (-1);
     return resM;
 }
References LinMath::Matrix::columns, LinMath::Matrix::invert(), permuteMatrix(), LinMath::Matrix::rows, LinMath::Matrix::subMatrix(), and LinMath::Matrix::transpose().
Referenced by solve_or_nan().
solve_or_nan()
LinMath::Matrix solve_or_nan (unsigned for1, unsigned for2, unsigned from1, unsigned from2, LinMath::Matrix & eq)
solve_for but catch any exception and NaN the matrix instead.
Parameters
for1
for2
from1
from2
eq
Returns
Definition at line 182 of file NetworkSolverTwoport.cpp.
{
     try {
         LinMath::Matrix m = solve_for(for1, for2, from1, from2, eq);
         return m;
     }
     catch (const LinMath::InvertException&) {
         LinMath::Matrix m(2, 2);
         m(0, 0) = std::numeric_limits<double>::quiet_NaN();
         m(1, 0) = std::numeric_limits<double>::quiet_NaN();
         m(0, 1) = std::numeric_limits<double>::quiet_NaN();
         m(1, 1) = std::numeric_limits<double>::quiet_NaN();
         return m;
     }
 }
References solve_for().
Referenced by Analyzer::Network::Solvers::NetworkSolverTwoport::solve().