name: Deploy to GitHub Pages
on:
  push:	
    branches:	
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - name: Generate documentation 
      uses: mattnotmitt/doxygen-action@v1
      with:
        working-directory: 'analyzer'
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:sasszem/jelek.git
        BRANCH: gh-pages
        FOLDER: analyzer/docs/html
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        MESSAGE: "Update from {sha}\nOriginal message:\n{msg}"